jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Godot Export
        uses: firebelley/godot-export@v2.4.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_export_templates.tpz
          relative_project_path: ./

on: push